const faqs = [
  {
    question: "What is USST and how does it work?",
    answer:
      "USST is a stablecoin backed by real-world assets. Users mint USST by depositing approved RWA tokens as collateral. This collateral remains deposited to support the USST supply while USST can be freely used, transferred, or spent.",
  },
  {
    question: "What is Yield(YLD) and where does it come from?",
    answer:
      "YLD is the yield generated by the real-world assets backing USST. As long as USST is in use, the underlying assets continue to generate yield, which accrues automatically. Users can view their YLD, claim it, or let it continue accruing over time.",
  },
];

export default function AboutSTBL() {
  return (
    <div className="flex flex-col gap-4 w-full">
      <h2 className="font-[var(--font-heading)] font-medium text-2xl leading-[1.2] tracking-tight" style={{ fontFeatureSettings: "'calt' 0, 'liga' 0" }}>
        About STBL
      </h2>

      <div className="flex flex-col gap-4">
        {faqs.map((faq, i) => (
          <div key={i}>
            <div className="flex flex-col gap-2">
              <p className="font-[var(--font-body)] font-medium text-base leading-[1.2] tracking-tight" style={{ fontFeatureSettings: "'calt' 0, 'liga' 0" }}>
                {faq.question}
              </p>
              <p className="text-sm leading-[1.4] tracking-tight text-black-400">
                {faq.answer}
              </p>
            </div>
            {i < faqs.length - 1 && <div className="h-px bg-black-15 mt-4" />}
          </div>
        ))}
      </div>
    </div>
  );
}
